(()=>{
const embedded=new URLSearchParams(location.search).get('embedded')==='1';
if(!embedded){const q=new URLSearchParams(location.search);q.set('view','library');location.replace('/constellations?'+q);return;}
document.body.classList.add('embedded-library');
'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);let project=params.get('project')||'demo',lane=params.get('lane')||'',offset=null,data=null,selected=null,timer=null,sequence=0;const opened=new Map();let team=lane?(params.get('team')??'researcher'):'',contextUI=null,reviewFingerprint=null,scopeGeneration=0,viewSequence=0;
const node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};const button=(text,run)=>{const b=node('button','',text);b.onclick=run;return b;};
let selectedVersion='',restoredLibrary=null;
const readingKey=()=> 'switchboard.library-reading.v1.'+project+'.'+lane+'.'+team;
function saveReading(){try{localStorage.setItem(readingKey(),JSON.stringify({query:$('query').value,kind:$('kind-filter').value,selected,version:selectedVersion,previewTop:$('preview').scrollTop,resultsTop:document.querySelector('.library-results').scrollTop}));}catch{}}
function readReading(){try{restoredLibrary=JSON.parse(localStorage.getItem(readingKey()))||{};}catch{restoredLibrary={};}$('query').value=String(restoredLibrary.query||'').slice(0,300);$('kind-filter').value=restoredLibrary.kind||'';}
window.addEventListener('pagehide',saveReading);readReading();
const route=()=>'/constellations?project='+encodeURIComponent(project)+(lane?'&lane='+encodeURIComponent(lane):'');$('back-workflow').href=route();
async function post(op,item={}){const r=await fetch('/api/workflow',{cache:'no-store'}),w=await r.json();if(!r.ok)throw Error('Cannot reach the local workflow');const response=await fetch('/api/library/'+op,{method:'POST',headers:{'Content-Type':'application/json','X-KE-Board-Token':w.controlToken},body:JSON.stringify(item)});const out=await response.json();if(!response.ok)throw Error(out.error);return out;}
function status(s){const progress=$('index-progress'),done=s.progress?.completed,total=s.progress?.total;const measured=Number.isFinite(done)&&Number.isFinite(total)&&total>0&&done>=0&&done<=total;progress.hidden=!measured;if(measured){progress.max=total;progress.value=done;progress.title=done+' / '+total+' source units indexed · '+s.status+' · '+(s.updatedAt||s.finishedAt||s.startedAt||'Timestamp unavailable')+' · Index work is separate from librarian review and adopted scope';progress.setAttribute('aria-valuetext',done+' of '+total+' source units indexed');}$('index-status').textContent=s.status==='running'?'Indexing '+s.progress.completed+' / '+s.progress.total+' sources':s.status==='completed'?'Updated '+new Date(s.finishedAt).toLocaleTimeString():s.status==='failed'?'Index needs attention':s.status==='interrupted'?'Index interrupted · refresh to retry':s.status==='unavailable'?'Index status unavailable':'Not indexed · use Refresh sources';$('coverage').textContent=(s.cappedSources?.length?'Partial coverage · ':'')+(data?.sources.length||0)+' connected locations';}
async function load(more=false){const run=++sequence;try{const query=new URLSearchParams({project,lane,team,q:$('query').value,kind:$('kind-filter').value,offset:more?offset||0:0});const r=await fetch('/api/library?'+query,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(run!==sequence)return;data=d;offset=d.nextOffset;$('library-error').hidden=true;window.LibraryServicePanel?.load(project,lane,team);$('library-context').textContent=(d.projects.find(x=>x.id===project)?.name||project)+(lane?' / '+(d.lanes.find(x=>x.id===lane)?.name||lane):' / ALL WORKSTREAMS');$('count').textContent=d.total.toLocaleString()+' records';$('review-count').textContent=d.reviewCount+' library reviews';$('lane-filter').replaceChildren(new Option('All workstreams',''),...d.lanes.map(l=>new Option(l.name,l.id)));$('lane-filter').value=lane;if(!more)$('results').replaceChildren();for(const item of d.items){const b=node('button','library-result');b.dataset.itemId=item.id;b.setAttribute('aria-pressed',String(item.id===selected));const meta=node('div','item-meta');meta.append(node('span','tag',item.kind),node('span','',d.lanes.find(l=>l.id===item.lane)?.name||'Project library'));b.append(meta,node('strong','',item.title),node('span','item-meta',item.state),node('div','excerpt',item.excerpt));b.onclick=()=>show(item.id);$('results').append(b);}if(!d.total){$('results').append(node('p','status',d.status.status==='running'?'Sources are being indexed…':'No records match this search.'));}$('more').hidden=offset===null;status(d.status);clearTimeout(timer);if(['running','starting'].includes(d.status.status))timer=setTimeout(()=>load(),1500);}catch(e){$('library-error').hidden=false;$('library-error').textContent=e.message;}}
async function show(id,version=''){const run=++viewSequence,generation=scopeGeneration;try{const r=await fetch('/api/library/item?'+new URLSearchParams({id,version,project,lane,team}),{cache:'no-store'});const item=await r.json();if(!r.ok)throw Error(item.error);if(run!==viewSequence||generation!==scopeGeneration)return;if(item.project!==project||(lane&&item.lane&&item.lane!==lane)||(team&&item.team&&item.team!==team))throw Error('This record belongs to a different library scope');selected=id;selectedVersion=item.sha;opened.set(id,{id,sha:item.sha});document.querySelectorAll('.library-result').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.itemId===id)));const p=$('preview');p.replaceChildren(button('← Results',()=>$('library-content').classList.remove('show-preview')),node('p','item-meta',item.kind+' · '+item.state),node('h2','',item.title));const tools=node('div','preview-tools');tools.append(button('Copy citation',async()=>{await navigator.clipboard.writeText(item.citation);tools.firstChild.textContent='Citation copied';}));if(item.versions.length>1){const select=node('select');select.setAttribute('aria-label','Document version');item.versions.forEach(v=>select.append(new Option(new Date(v.captured).toLocaleString()+' · '+v.sha.slice(0,8),v.sha)));select.value=item.sha;select.onchange=()=>show(id,select.value);tools.append(select);}p.append(tools,node('div','source-path',item.path||item.basis),node('div','item-meta','SHA-256 '+(item.sha?.slice(0,16)||'unavailable')));p.append(documentView(item));$('library-content').classList.add('show-preview');p.scrollTop=restoredLibrary?.selected===id&&restoredLibrary.version===item.sha?Number(restoredLibrary.previewTop)||0:0;restoredLibrary=null;saveReading();}catch(e){if(run===viewSequence&&generation===scopeGeneration)$('preview').replaceChildren(node('p','reader-error',e.message));}}
$('query').oninput=()=>{saveReading();clearTimeout(timer);timer=setTimeout(()=>load(),220);};$('kind-filter').onchange=()=>{saveReading();load();};$('lane-filter').onchange=()=>changeScope(project,$('lane-filter').value);$('more').onclick=()=>load(true);$('refresh-library').onclick=async()=>{try{await post('refresh');load();}catch(e){$('library-error').textContent=e.message;$('library-error').hidden=false;}};
$('sources').onclick=()=>{++viewSequence;const p=$('preview');p.replaceChildren(button('← Results',()=>$('library-content').classList.remove('show-preview')),node('h2','','Connected sources'));for(const s of data?.sources||[]){const row=node('div','source-row',s.basis);row.append(node('code','',s.path));p.append(row);}$('library-content').classList.add('show-preview');};
for(const id of ['note','review']){const dialog=$(id+'-dialog'),form=$(id+'-form');form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('button.primary');submit.disabled=true;try{const values=Object.fromEntries(new FormData(form));const contextFingerprint=id==='review'?reviewFingerprint:undefined;const payload={...values,project,lane,team,query:$('query').value,items:[...opened.values()],contextFingerprint};const serialized=JSON.stringify(payload);if(form.dataset.payload!==serialized){form.dataset.requestId=crypto.randomUUID();form.dataset.payload=serialized;}await post(id,{...payload,requestId:form.dataset.requestId});delete form.dataset.requestId;delete form.dataset.payload;dialog.close();form.reset();await load();setTimeout(()=>load(),1500);}catch(e){form.querySelector('.form-error').textContent=e.message;}finally{submit.disabled=false;}};}
$('new-note').onclick=()=>$('note-dialog').showModal();$('review').onclick=async()=>{const generation=scopeGeneration;try{reviewFingerprint=(await contextUI.load()).fingerprint;if(generation!==scopeGeneration)return;}catch(e){if(generation===scopeGeneration){$('library-error').textContent=e.message;$('library-error').hidden=false;}return;}$('review-summary').textContent=opened.size+' opened sources · '+($('query').value||'Current collection');$('review-dialog').showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
window.addEventListener('switchboard-project',e=>changeScope(e.detail.project,''));
let workspaceUI=LibraryWorkspace.create({scope:()=>({project,lane,team}),post,node,button,changeScope,openRecord:(id,sha)=>{setMode('records');show(id,sha);},pins:()=>[...opened.values()]});
let mode=params.get('item')||params.get('view')==='context'?'records':params.get('panel')||'workspace';
function notifyScope(){if(parent!==window)parent.postMessage({type:'switchboard-library-scope',project,lane,team,panel:mode},location.origin);}
function setMode(next){mode=['records','requirements'].includes(next)?next:'workspace';document.body.classList.toggle('workspace-active',mode!=='records');$('library-workspace').hidden=mode==='records';$('workspace-mode').setAttribute('aria-pressed',String(mode==='workspace'));document.body.classList.toggle('requirements-active',mode==='requirements');$('requirements-mode').setAttribute('aria-pressed',String(mode==='requirements'));$('records-mode').setAttribute('aria-pressed',String(mode==='records'));const u=new URL(location.href);u.searchParams.set('panel',mode);history.replaceState(null,'',u);notifyScope();if(mode!=='records')workspaceUI.refresh();else workspaceUI.invalidate();}
$('requirements-mode').onclick=()=>setMode('requirements');$('workspace-mode').onclick=()=>setMode('workspace');$('records-mode').onclick=()=>setMode('records');setMode(mode);
setupContext();load().then(()=>{if(params.get('item'))show(params.get('item'));else if(params.get('view')==='context'&&contextUI)contextUI.render();else if(restoredLibrary?.selected)show(restoredLibrary.selected,restoredLibrary.version||'');});setInterval(()=>{if(!document.hidden)load();},60000);

function changeScope(nextProject,nextLane,nextTeam){
 saveReading();project=nextProject;lane=nextLane;team=lane?(nextTeam??'researcher'):'';workspaceUI.invalidate();
 ++scopeGeneration;++viewSequence;++sequence;clearTimeout(timer);
 selected=null;opened.clear();reviewFingerprint=null;offset=null;data=null;
 for(const id of ['note','review']){const dialog=$(id+'-dialog'),form=$(id+'-form');if(dialog.open)dialog.close();form.reset();delete form.dataset.requestId;delete form.dataset.payload;form.querySelector('.form-error').textContent='';}
 $('preview').replaceChildren();$('results').replaceChildren();$('library-content').classList.remove('show-preview');
 const u=new URL(location.href);u.searchParams.set('project',project);
 for(const [key,value]of [['lane',lane],['team',team]]){if(value||key==='team'&&lane)u.searchParams.set(key,value);else u.searchParams.delete(key);}
 u.searchParams.delete('item');u.searchParams.delete('view');history.replaceState(null,'',u);
 $('back-workflow').href=route();readReading();setupContext();notifyScope();if(mode!=='records')workspaceUI.refresh();load().then(()=>{if(restoredLibrary?.selected)show(restoredLibrary.selected,restoredLibrary.version||'');});
}
function setupContext(){
 for(const kind of ['Project context','Workstream context','Founding scope','Scope revision','Evidence disposition'])if(!Array.from($('kind-filter').options).some(option=>option.value===kind))$('kind-filter').append(new Option(kind,kind));
 const generation=scopeGeneration;
 contextUI=TeamLibrary.create({project,lane,team,post,node,button,begin:()=>++viewSequence,isActive:run=>generation===scopeGeneration&&run===viewSequence});
 $('team-context').hidden=false;$('team-context').textContent=team?'Team context':lane?'Workstream context':'Project context';
 $('team-context').onclick=()=>contextUI.render();
}

function documentView(item){const body=node('div','document-body');let parsed=null;try{parsed=JSON.parse(item.body);}catch{}if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed)){const entries=Object.entries(parsed);for(const [key,value]of entries){if(['objective','title'].includes(key)&&value===item.title)continue;const field=node('section','document-field');field.append(node('strong','',key.replace(/_/g,' ')));if(value&&typeof value==='object'){const details=node('details');details.append(node('summary','',Array.isArray(value)?value.length+' entries':'View details'),node('pre','',JSON.stringify(value,null,2)));field.append(details);}else field.append(node('div','',value===null?'Not recorded':String(value)));body.append(field);}}else body.textContent=item.body||'No text preview is available for this source.';return body;}

})();
